import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <div className={`  antialiased h-screen flex`}>
       <div className="sm:w-[14%] max-sm:w-[20%] h-full  bg-red-300">
        left
       </div>
       <div className="w-[86%] h-full bg-green-300">
        right
       </div>
       
   </div>
  );
}
