import Menu from "@/components/Menu";
import Navbar from "@/components/Navbar";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <div className={`  antialiased h-screen flex`}>
       <div className="sm:w-[14%]  max-sm:w-[20%] py-6 h-full  ">
        <div className="flex px-4 max-md:hidden  gap-1">
                <span className="text-black text-lg">School Dev</span>
        <Image src="/logo.png" width={40} height={50} alt="logo" />
        </div>
        <Menu/>
       </div>
       <div className="w-[86%] h-full ">
        <Navbar/>
        {children}
       </div>
       
   </div>
  );
}
